package cn.angelbell.oa.mapper.leader;

import cn.angelbell.oa.entity.Leader;
import cn.angelbell.oa.entity.LeaderExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int countByExample(LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int deleteByExample(LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer leaderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int insert(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int insertSelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    List<Leader> selectByExample(LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    Leader selectByPrimaryKey(Integer leaderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Leader record, @Param("example") LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Leader record, @Param("example") LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Leader record);
    
    /**
     * 
     * @Title: getList
     * @Description: 获取所有领导列表
     * @return
     * @throws Exception
     */
    List<Leader> getList() throws Exception;
}