package cn.angelbell.oa.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comment_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Comment {
    /**
     * Database Column Remarks:
     *   点评id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * Database Column Remarks:
     *   评价学生姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   学生表现等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * Database Column Remarks:
     *   点评人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.commentator
     *
     * @mbggenerated
     */
    private String commentator;

    /**
     * Database Column Remarks:
     *   点评时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.intime
     *
     * @mbggenerated
     */
    private Date intime;

    /**
     * Database Column Remarks:
     *   点评正文内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.comment_id
     *
     * @return the value of comment_info.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.comment_id
     *
     * @param commentId the value for comment_info.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.name
     *
     * @return the value of comment_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.name
     *
     * @param name the value for comment_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.grade
     *
     * @return the value of comment_info.grade
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.grade
     *
     * @param grade the value for comment_info.grade
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.commentator
     *
     * @return the value of comment_info.commentator
     *
     * @mbggenerated
     */
    public String getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.commentator
     *
     * @param commentator the value for comment_info.commentator
     *
     * @mbggenerated
     */
    public void setCommentator(String commentator) {
        this.commentator = commentator == null ? null : commentator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.intime
     *
     * @return the value of comment_info.intime
     *
     * @mbggenerated
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.intime
     *
     * @param intime the value for comment_info.intime
     *
     * @mbggenerated
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.content
     *
     * @return the value of comment_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.content
     *
     * @param content the value for comment_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}