package cn.angelbell.oa.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table leader_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Leader {
    /**
     * Database Column Remarks:
     *   领导ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.leader_id
     *
     * @mbggenerated
     */
    private Integer leaderId;

    /**
     * Database Column Remarks:
     *   领导姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   领导性别(0女；1男)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * Database Column Remarks:
     *   电子邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   所属校区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * Database Column Remarks:
     *   领导照片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * Database Column Remarks:
     *   入职时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_info.intime
     *
     * @mbggenerated
     */
    private Date intime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.leader_id
     *
     * @return the value of leader_info.leader_id
     *
     * @mbggenerated
     */
    public Integer getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.leader_id
     *
     * @param leaderId the value for leader_info.leader_id
     *
     * @mbggenerated
     */
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.name
     *
     * @return the value of leader_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.name
     *
     * @param name the value for leader_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.sex
     *
     * @return the value of leader_info.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.sex
     *
     * @param sex the value for leader_info.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.email
     *
     * @return the value of leader_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.email
     *
     * @param email the value for leader_info.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.phone
     *
     * @return the value of leader_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.phone
     *
     * @param phone the value for leader_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.school
     *
     * @return the value of leader_info.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.school
     *
     * @param school the value for leader_info.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.picture
     *
     * @return the value of leader_info.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.picture
     *
     * @param picture the value for leader_info.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_info.intime
     *
     * @return the value of leader_info.intime
     *
     * @mbggenerated
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_info.intime
     *
     * @param intime the value for leader_info.intime
     *
     * @mbggenerated
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }
}