package cn.angelbell.oa.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   操作日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin_log
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Log {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.log_id
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * Database Column Remarks:
     *   操作描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   操作用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * Database Column Remarks:
     *   消耗时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.spend_time
     *
     * @mbggenerated
     */
    private Date spendTime;

    /**
     * Database Column Remarks:
     *   根路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.base_path
     *
     * @mbggenerated
     */
    private String basePath;

    /**
     * Database Column Remarks:
     *   URI
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.uri
     *
     * @mbggenerated
     */
    private String uri;

    /**
     * Database Column Remarks:
     *   URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   请求类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * Database Column Remarks:
     *   用户标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.user_agent
     *
     * @mbggenerated
     */
    private String userAgent;

    /**
     * Database Column Remarks:
     *   IP地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   权限值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.permissions
     *
     * @mbggenerated
     */
    private String permissions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.parameter
     *
     * @mbggenerated
     */
    private String parameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.log_id
     *
     * @return the value of admin_log.log_id
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.log_id
     *
     * @param logId the value for admin_log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.description
     *
     * @return the value of admin_log.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.description
     *
     * @param description the value for admin_log.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.username
     *
     * @return the value of admin_log.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.username
     *
     * @param username the value for admin_log.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.start_time
     *
     * @return the value of admin_log.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.start_time
     *
     * @param startTime the value for admin_log.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.spend_time
     *
     * @return the value of admin_log.spend_time
     *
     * @mbggenerated
     */
    public Date getSpendTime() {
        return spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.spend_time
     *
     * @param spendTime the value for admin_log.spend_time
     *
     * @mbggenerated
     */
    public void setSpendTime(Date spendTime) {
        this.spendTime = spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.base_path
     *
     * @return the value of admin_log.base_path
     *
     * @mbggenerated
     */
    public String getBasePath() {
        return basePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.base_path
     *
     * @param basePath the value for admin_log.base_path
     *
     * @mbggenerated
     */
    public void setBasePath(String basePath) {
        this.basePath = basePath == null ? null : basePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.uri
     *
     * @return the value of admin_log.uri
     *
     * @mbggenerated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.uri
     *
     * @param uri the value for admin_log.uri
     *
     * @mbggenerated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.url
     *
     * @return the value of admin_log.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.url
     *
     * @param url the value for admin_log.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.method
     *
     * @return the value of admin_log.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.method
     *
     * @param method the value for admin_log.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.user_agent
     *
     * @return the value of admin_log.user_agent
     *
     * @mbggenerated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.user_agent
     *
     * @param userAgent the value for admin_log.user_agent
     *
     * @mbggenerated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.ip
     *
     * @return the value of admin_log.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.ip
     *
     * @param ip the value for admin_log.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.permissions
     *
     * @return the value of admin_log.permissions
     *
     * @mbggenerated
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.permissions
     *
     * @param permissions the value for admin_log.permissions
     *
     * @mbggenerated
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions == null ? null : permissions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.parameter
     *
     * @return the value of admin_log.parameter
     *
     * @mbggenerated
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.parameter
     *
     * @param parameter the value for admin_log.parameter
     *
     * @mbggenerated
     */
    public void setParameter(String parameter) {
        this.parameter = parameter == null ? null : parameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.result
     *
     * @return the value of admin_log.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.result
     *
     * @param result the value for admin_log.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}