package cn.angelbell.oa.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table parent_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Parent {
    /**
     * Database Column Remarks:
     *   家长id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_info.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   家长姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   与孩子的关系
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_info.relationship
     *
     * @mbggenerated
     */
    private String relationship;

    /**
     * Database Column Remarks:
     *   家长联系方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   家庭住址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   备用联系人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_info.spareName
     *
     * @mbggenerated
     */
    private String sparename;

    /**
     * Database Column Remarks:
     *   备用联系人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent_info.sparePhone
     *
     * @mbggenerated
     */
    private String sparephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_info.parent_id
     *
     * @return the value of parent_info.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_info.parent_id
     *
     * @param parentId the value for parent_info.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_info.name
     *
     * @return the value of parent_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_info.name
     *
     * @param name the value for parent_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_info.relationship
     *
     * @return the value of parent_info.relationship
     *
     * @mbggenerated
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_info.relationship
     *
     * @param relationship the value for parent_info.relationship
     *
     * @mbggenerated
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_info.phone
     *
     * @return the value of parent_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_info.phone
     *
     * @param phone the value for parent_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_info.address
     *
     * @return the value of parent_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_info.address
     *
     * @param address the value for parent_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_info.spareName
     *
     * @return the value of parent_info.spareName
     *
     * @mbggenerated
     */
    public String getSparename() {
        return sparename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_info.spareName
     *
     * @param sparename the value for parent_info.spareName
     *
     * @mbggenerated
     */
    public void setSparename(String sparename) {
        this.sparename = sparename == null ? null : sparename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent_info.sparePhone
     *
     * @return the value of parent_info.sparePhone
     *
     * @mbggenerated
     */
    public String getSparephone() {
        return sparephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent_info.sparePhone
     *
     * @param sparephone the value for parent_info.sparePhone
     *
     * @mbggenerated
     */
    public void setSparephone(String sparephone) {
        this.sparephone = sparephone == null ? null : sparephone.trim();
    }
}