package cn.angelbell.oa.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table student_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Student {
    /**
     * Database Column Remarks:
     *   学生id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * Database Column Remarks:
     *   学生姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   学生性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * Database Column Remarks:
     *   所属班级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.subordinateclass
     *
     * @mbggenerated
     */
    private String subordinateclass;

    /**
     * Database Column Remarks:
     *   所属校区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.subordinateschool
     *
     * @mbggenerated
     */
    private String subordinateschool;

    /**
     * Database Column Remarks:
     *   外键，关联家长信息表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   入学时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.intime
     *
     * @mbggenerated
     */
    private Date intime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_id
     *
     * @return the value of student_info.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_id
     *
     * @param studentId the value for student_info.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.name
     *
     * @return the value of student_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.name
     *
     * @param name the value for student_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.sex
     *
     * @return the value of student_info.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.sex
     *
     * @param sex the value for student_info.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.subordinateclass
     *
     * @return the value of student_info.subordinateclass
     *
     * @mbggenerated
     */
    public String getSubordinateclass() {
        return subordinateclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.subordinateclass
     *
     * @param subordinateclass the value for student_info.subordinateclass
     *
     * @mbggenerated
     */
    public void setSubordinateclass(String subordinateclass) {
        this.subordinateclass = subordinateclass == null ? null : subordinateclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.subordinateschool
     *
     * @return the value of student_info.subordinateschool
     *
     * @mbggenerated
     */
    public String getSubordinateschool() {
        return subordinateschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.subordinateschool
     *
     * @param subordinateschool the value for student_info.subordinateschool
     *
     * @mbggenerated
     */
    public void setSubordinateschool(String subordinateschool) {
        this.subordinateschool = subordinateschool == null ? null : subordinateschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.parent_id
     *
     * @return the value of student_info.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.parent_id
     *
     * @param parentId the value for student_info.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.intime
     *
     * @return the value of student_info.intime
     *
     * @mbggenerated
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.intime
     *
     * @param intime the value for student_info.intime
     *
     * @mbggenerated
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }
}