package cn.angelbell.oa.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table teacher_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Teacher {
    /**
     * Database Column Remarks:
     *   教师编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.teacher_id
     *
     * @mbggenerated
     */
    private Integer teacherId;

    /**
     * Database Column Remarks:
     *   教师昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * Database Column Remarks:
     *   教师性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * Database Column Remarks:
     *   教师邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   教师电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   教师所带班级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.takeclass
     *
     * @mbggenerated
     */
    private String takeclass;

    /**
     * Database Column Remarks:
     *   教师所属校区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * Database Column Remarks:
     *   教师照片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * Database Column Remarks:
     *   入职时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_info.intime
     *
     * @mbggenerated
     */
    private Date intime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.teacher_id
     *
     * @return the value of teacher_info.teacher_id
     *
     * @mbggenerated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.teacher_id
     *
     * @param teacherId the value for teacher_info.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.nickname
     *
     * @return the value of teacher_info.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.nickname
     *
     * @param nickname the value for teacher_info.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.realname
     *
     * @return the value of teacher_info.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.realname
     *
     * @param realname the value for teacher_info.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.sex
     *
     * @return the value of teacher_info.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.sex
     *
     * @param sex the value for teacher_info.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.email
     *
     * @return the value of teacher_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.email
     *
     * @param email the value for teacher_info.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.phone
     *
     * @return the value of teacher_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.phone
     *
     * @param phone the value for teacher_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.takeclass
     *
     * @return the value of teacher_info.takeclass
     *
     * @mbggenerated
     */
    public String getTakeclass() {
        return takeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.takeclass
     *
     * @param takeclass the value for teacher_info.takeclass
     *
     * @mbggenerated
     */
    public void setTakeclass(String takeclass) {
        this.takeclass = takeclass == null ? null : takeclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.school
     *
     * @return the value of teacher_info.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.school
     *
     * @param school the value for teacher_info.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.picture
     *
     * @return the value of teacher_info.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.picture
     *
     * @param picture the value for teacher_info.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_info.intime
     *
     * @return the value of teacher_info.intime
     *
     * @mbggenerated
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_info.intime
     *
     * @param intime the value for teacher_info.intime
     *
     * @mbggenerated
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }
}