package cn.angelbell.oa.entity;

/**
 * Database Table Remarks:
 *   用户角色关联表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin_user_role
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class UserAndRole {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.user_role_id
     *
     * @mbggenerated
     */
    private Integer userRoleId;

    /**
     * Database Column Remarks:
     *   用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   角色编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_role.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.user_role_id
     *
     * @return the value of admin_user_role.user_role_id
     *
     * @mbggenerated
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.user_role_id
     *
     * @param userRoleId the value for admin_user_role.user_role_id
     *
     * @mbggenerated
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.user_id
     *
     * @return the value of admin_user_role.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.user_id
     *
     * @param userId the value for admin_user_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_role.role_id
     *
     * @return the value of admin_user_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_role.role_id
     *
     * @param roleId the value for admin_user_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}