package cn.angelbell.oa.mapper.role;

import cn.angelbell.oa.entity.RoleAndPermission;
import cn.angelbell.oa.entity.RoleAndPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAndPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int countByExample(RoleAndPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int deleteByExample(RoleAndPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int insert(RoleAndPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(RoleAndPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    List<RoleAndPermission> selectByExample(RoleAndPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    RoleAndPermission selectByPrimaryKey(Integer rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleAndPermission record, @Param("example") RoleAndPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleAndPermission record, @Param("example") RoleAndPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleAndPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleAndPermission record);
}