package cn.angelbell.oa.mapper.role;

import cn.angelbell.oa.entity.UserAndRole;
import cn.angelbell.oa.entity.UserAndRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAndRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int countByExample(UserAndRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(UserAndRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int insert(UserAndRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int insertSelective(UserAndRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    List<UserAndRole> selectByExample(UserAndRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    UserAndRole selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserAndRole record, @Param("example") UserAndRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserAndRole record, @Param("example") UserAndRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAndRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAndRole record);
}