package cn.angelbell.oa.mapper.access;

import cn.angelbell.oa.entity.Visitnet;
import cn.angelbell.oa.entity.VisitnetExample;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface VisitnetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int countByExample(VisitnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int deleteByExample(VisitnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int insert(Visitnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int insertSelective(Visitnet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    List<Visitnet> selectByExample(VisitnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    Visitnet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Visitnet record, @Param("example") VisitnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Visitnet record, @Param("example") VisitnetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Visitnet record);

    /**
     * 获取热力图信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Visitnet record);
    
    /**
     * 获取热力图信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitnet
     *
     * @mbggenerated
     */
    List<HashMap<String, Object>> getVisitorMap();
}